#!/bin/bash
#
#

DIRNAME=`basename "$PWD"`

OUTFILES=""
for INFILE in datasheet_page*.svg; do
	BASENAME=`basename "$INFILE"`
	OUTFILE="/tmp/${BASENAME}.pdf"
	if [ ! -f "$INFILE" ]; then
		break
	fi
	echo "$INFILE -> $OUTFILE"
	inkscape "$INFILE" -o "$OUTFILE"	
	OUTFILES="${OUTFILES} ${OUTFILE}"
done

if [ "$OUTFILES" == "" ]; then
	echo "No input files found in current working directory."
	exit 1
fi

echo "$OUTFILES"
pdftk $OUTFILES cat output datasheet_${DIRNAME}.pdf
rm -f "$OUTFILES"
