#!/bin/bash
#
#

if [ "$1" == "16" ]; then
	PART="NMC27C16B@DIP24"
elif [ "$1" == "32" ]; then
	PART="NMC27C32B@DIP24"
else
	echo "$0 [16|32]"
	echo "specifies if the 27C16 or 27C32 is being programmed."
	exit 1
fi
minipro -p "$PART" -s -u --pulse=50000 -w firmware.bin
